### ISSUE TITLE
Fabric Loader Support

### ISSUE THREAD

**Issue by spectrapulse** [sudolev/CreateInteriorsMod#14]
Hi There! Coming from Create: Bells And Whistles. Adds a ton of nice items to the game and I definitely appreciate that it exists and is maintained by you 👍

Anyways, now onto the issue itself. This mod looks interesting too but is unfortunately not available on Fabric at this time. I've already noticed that there's branches in this repo that would indicate that a Fabric version of this Mod is being worked on with recent commits but I wanted to ask if there's any expected time frame on when the first version could be released. I'm not pushy and I would understand if there's no ETA on it but I'm definitely interested on how it is coming along and what the state of Fabric support is at the moment.

Additionally I'd like to ask if this issue can be left open as long there's no Fabric release, it makes it may make it easier to track progress as following projects and maybe can be a great issue to inform people from the future who happen to also be interested in Fabric support.

Keep up the good work! Love your work.

**Comment by a0ax** [comment]
Sure. So the fabric versions are finished except for the mixins (which make the big chairs behave like big chairs, among other things). I'll leave the issue open and update you if/when things change!

**Comment by rhysdh540** [comment]
@sudolev did you ever publish this

**Comment by a0ax** [comment]
Fabric version? No iirc the mixins didn't work

You should have publishing perms on curse + modrinth btw

**Comment by itsdeadfrosty** [comment]
there is a fabric api and connector now tho

**Comment by rhysdh540** [comment]
Working Fabric support now exists for Minecraft 1.20.1 (pending testing and publishing). Support for older Minecraft versions will be added soon.

**Comment by rhysdh540** [comment]
soon™

**Comment by rhysdh540** [comment]
fabric is now out on modrinth, github releases, and curseforge!
