### ISSUE TITLE
crashes during launch with mod installed

### ISSUE THREAD

**Issue by itsdeadfrosty** [sudolev/CreateInteriorsMod#15]
works fine without

Currently working on a mod pack that as of right now includes over 600 mods it's been tried and tested and it works great however attempting to install this mod doesn't even let it get past launch

it flags this mod

https://github.com/alejandrocoria/MapFrontiers

but that mod runs fine, its this interiors mod that breaks the pack

so maybe a conflict? idk

[crash-2024-02-25_15.02.42-fml.txt](https://github.com/sudolev/CreateInteriorsMod/files/14397696/crash-2024-02-25_15.02.42-fml.txt)

[latest.log](https://github.com/sudolev/CreateInteriorsMod/files/14397697/latest.log)

**Comment by rhysdh540** [comment]
interiors literally never even shows up in the log except in the mods list
can you verify that this actually only happens consistently with interiors installed, and this isn't just aanother random bug?

**Comment by a0ax** [comment]
Looking both logs you provided, it seems to be a conflict between mapfrontiers and drippy loading screen. Create Interiors isn't mentioned at all outside of it being  loaded. 

![Screenshot_20240225_143237_Firefox.jpg](https://github.com/sudolev/CreateInteriorsMod/assets/61996958/8672bbb7-3910-4335-98be-322b2e3f0f61)

I can look into it more if you like, but it seems to be unrelated to interiors at first glance.

**Comment by itsdeadfrosty** [comment]
i just removed it cause lit everything hates map frontiers

**Comment by a0ax** [comment]
Open an issue here: https://github.com/alejandrocoria/MapFrontiers. This doesn't look to have anything to do with Interiors.
