### ISSUE TITLE
Missing block/item tags for all Kelp Seat and chairs.

### ISSUE THREAD

**Issue by Mickeon** [sudolev/CreateInteriorsMod#16]
For both item and block tags:
- `create:seats` should include `interiors:kelp_seat`;
- `interiors:chairs` should include `interiors:kelp_chair`;
- `interiors:floor_chairs` should include `interiors:kelp_floor_chair`.

Currently, none of the above is the case, which is a small annoyance (for example, when grouping items with REI).

**Comment by rhysdh540** [comment]
The reason kelp seats aren't included is for crafting—you shouldn't be able to craft regular wool seats/chairs from kelp chairs, or vice versa.

**Comment by a0ax** [comment]
What rdh said 😁
