### ISSUE TITLE
Broken tags?

### ISSUE THREAD

**Issue by Looxond** [sudolev/CreateInteriorsMod#18]
![2024-07-01_14 51 50](https://github.com/aesefficio/CreateInteriorsMod/assets/29359853/dc0bb450-5e38-4a7b-bf55-27595bd47182)

Dunno if its a compat issue or something else

**Comment by rhysdh540** [comment]
what platform/minecraft version?

**Comment by Looxond** [comment]
> what platform/minecraft version?

1.20.1 version interiors-0.5.3 forge-mc1.20.1

**Comment by rhysdh540** [comment]
oh it's because we do datagen on fabric but the tag on forge is different -_-
will fix soon™

**Comment by a0ax** [comment]
Fixed in lil hotfix (not so hot) [v0.5.4](https://github.com/aesefficio/CreateInteriorsMod/releases/tag/v0.5.4-1.20.1). Up on modrinth & curseforge whenever they approve the file.

Thanks for the issue!
