### ISSUE TITLE
"Dye Depot" incompatibility

### ISSUE THREAD

**Issue by a0a7** [sudolev/CreateInteriorsMod#20]
Mod currently not compatible with Dye Depot
![image](https://github.com/user-attachments/assets/b34459cb-48cb-46f3-9a00-25bb063d5323)

**Comment by a0ax** [comment]
Made a compat resource pack

Download:
[Curseforge](https://legacy.curseforge.com/minecraft/texture-packs/create-dyes) | [Modrinth](https://modrinth.com/resourcepack/create-dyes)
