### ISSUE TITLE
[Bug] Dyeing floor chairs when placed changes them to regular Create seat.

### ISSUE THREAD

**Issue by DaRealSparky** [sudolev/CreateInteriorsMod#21]
Dyeing the floor chairs changes them to regular Create seats, requiring them to be re-crafted. Also, you can dye kelp seats into regular variants, but not the other way around, I.E. right clicking with a belt.

Versions:
- Minecraft 1.20.1
- Forge 47.3.7
- Create 0.5.1f
- Create: Interiors 0.5.4

**Comment by a0ax** [comment]
Ooh I didn't know this functionality existed, thanks for the issue! Will fix next version.

**Comment by rhysdh540** [comment]
fixed in 0.5.5
