### ISSUE TITLE
NoSuchMethod crash on startup [Forge]

### ISSUE THREAD

**Issue by pinkygrocket** [sudolev/CreateInteriorsMod#22]
[crash-2024-09-04_20.22.01-fml.txt](https://mclo.gs/CaXHHNW)

**Comment by rhysdh540** [comment]
This is being looked into.

**Comment by AqueleHaru** [comment]
same here, waiting for a update <3

**Comment by AqueleHaru** [comment]
any updates? 😭  needs to turn my server on

**Comment by rhysdh540** [comment]
I’ve discovered the cause of this issue, I will upload a hotfix very soon.

**Comment by rhysdh540** [comment]
v0.5.6, which fixes this issue, has been uploaded to Modrinth and is being approved on CurseForge. Thanks for the reports, everybody!

**Comment by LeModJy** [comment]
works fine
