### ISSUE TITLE
Input delay when sitting in chair

### ISSUE THREAD

**Issue by Nycto97** [sudoLev/CreateInteriorsMod#4]
Hey!

Love the mod, been checking this daily until it became available for 1.19.2.

Now, I noticed that when sitting in a chair, I experience a small input delay when looking around in game by moving my mouse.

Not a big deal, just letting you know.

If you would need my modlist, I'm glad to post it.

Thanks for the mod!

**Comment by sudoLev** [comment]
Hi, I appreciate the support!
Do you experience the same issue with Create mod seats, or only my chair blocks? Regardless, thank you for the issue!

**Comment by Nycto97** [comment]
After testing it seems like I have the issue with the Create mod seats as well.

**Comment by sudoLev** [comment]
In that case it isn't my fault and I can't do much to fix it. If you want, you can make an issue on the [Create git repo](https://github.com/Creators-of-Create/Create/issues), and make sure to share what hardware/OS you're running. Thank you!
