### ISSUE TITLE
Wrong position of the driver on a seat when in a moving contraption

### ISSUE THREAD

**Issue by Jerome226** [sudolev/CreateInteriorsMod#5]
![image](https://github.com/sudolev/CreateInteriorsMod/assets/55724525/36d4e61f-f82a-4699-9a01-5d07614d46c8)
Should be 0.34 blocks higher

**Comment by sudolev** [comment]
I'm very aware, it's just that I have to learn mixins to fix this bug. Will try to fix eventually.

Thanks for the issue!

**Comment by Jerome226** [comment]
> I'm very aware, it's just that I have to learn mixins to fix this bug. Will try to fix eventually.
> 
> Thanks for the issue!

Do you have any idea what code in Create cause this issue?

**Comment by sudolev** [comment]
Yeah, the seat height is hard-coded in the train component and I would have to make it not hard-coded. I don't know the class off the top of my head, but it's in there and I've looked at it.

**Comment by rhysdh540** [comment]
fixed by #10

**Comment by a0ax** [comment]
Thanks to @rhysdh540. Create: Interiors is now a glorious McFlurry! Fixed in [Release v0.5](https://github.com/sudolev/CreateInteriorsMod/releases/tag/v0.5).
