### ISSUE TITLE
 This is not a bug, this is localization into Russian.

### ISSUE THREAD

**Issue by rim4oo** [sudolev/CreateInteriorsMod#6]
[ru_ru.json](https://github.com/sudolev/CreateInteriorsMod/files/12906619/ru_ru.json)

**Comment by sudolev** [comment]
Thank you so very much for this translation! I've put it in the files for all of the different Minecraft versions and it will be a part of the next mod update.

I've also added a credit to you on the [Github page](https://github.com/sudolev/CreateInteriorsMod/blob/main/README.md), on [Curseforge](https://curseforge.com/minecraft/mc-mods/interiors) and on [Modrinth](https://modrinth.com/mod/interiors/settings/description). I really, really appreciate the translation, it means more than you know.

Thank you again, and have a wonderful day/night!!

🎉 🥳

**Comment by sudolev** [comment]
Hi, just want to let you know that I pushed new versions of the mods with Russian localization included. Thank you again!

**Comment by rim4oo** [comment]
[ru_ru.json](https://github.com/sudolev/CreateInteriorsMod/files/13239375/ru_ru.json)

I've corrected the translation a little.

**Comment by rim4oo** [comment]
❤❤

**Comment by a0ax** [comment]
> [ru_ru.json](https://github.com/sudolev/CreateInteriorsMod/files/13239375/ru_ru.json)
> I've corrected the translation a little.

Thank you! I've added it to all the versions and pushed a release with the new translation. Really appreciate it!
