### ISSUE TITLE
Wood breaking problem

### ISSUE THREAD

**Issue by janisl** [sudolev/CreateInteriorsMod#8]
After I updated the mod to 0.4 for 1.20.1 all wood blocks stopped considering axe as a valid tool and breaking with axe is the same as breaking with hand. Version 0.3.1 doesn't have this problem.

**Comment by sudolev** [comment]
Hi, thanks very much for the issue--this was a big oversight by me.

Fixed in v0.4.3, which is out now. Thank you again!
